GET http://0.0.0.0:8080/accounts?page=1&page_size=10

###

GET http://0.0.0.0:8080/accounts/494

###

POST http://0.0.0.0:8080/accounts

{
  "owner": "Rony",
  "currency": "USD"
}

###

POST http://0.0.0.0:8080/transfers

{
  "from_account_id": 178,
  "to_account_id": 180,
  "amount": 100,
  "currency": "CAD"
}